In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))
import pandas as pd

from src.data.data_fetcher import StockDataFetcher
fetcher = StockDataFetcher()

In [2]:
def print_nested_dict(data, indent=0):
    """
    Recursively prints a nested dictionary in a structured format.

    Args:
        data (dict): Dictionary to print.
        indent (int): Indentation level for formatting.
    """
    for key, value in data.items():
        if isinstance(value, dict):
            print(" " * indent + f"{key}:")
            print_nested_dict(value, indent + 4)
        else:
            print(" " * indent + f"{key}: {value}")

def test_full_stock_info(ticker: str):
    """
    Test function to fetch and print all stock information.

    Args:
        ticker (str): Stock symbol (e.g., 'AAPL')
    """
    fetcher = StockDataFetcher()
    
    result = fetcher.get_full_stock_info(ticker)

    print("\n" + "=" * 50)
    print(f"FULL STOCK DATA FOR: {ticker.upper()}")
    print("=" * 50 + "\n")

    # Check error first
    if result["error"]:
        print("Error:", result["error"])
        return

    # Print everything
    print_nested_dict(result)

# print(test_full_stock_info("AAPL"))

# testing validate ticker function

In [3]:
ticker = "aapl"

if fetcher.validate_ticker(ticker):
    print("Valid ticker ✅")
else:
    print("Invalid ticker ❌")

Valid ticker ✅

# testing fetch historical function

In [4]:
result = fetcher.fetch_historical("AAPL")

if result["error"]:
    print("Error:", result["error"])
else:
    df = result["data"]

df.head(5)

,open,high,low,close,volume,dividends,stock_splits
Date,,,,,,,
2025-04-24,204.000880,207.923785,202.059345,207.465775,47311000,0.0,0.0
2025-04-25,205.474435,208.839773,205.305175,208.371811,38222300,0.0,0.0
2025-04-28,209.088712,210.582203,206.559741,209.228104,38743100,0.0,0.0
2025-04-29,207.784388,211.318986,207.465770,210.293457,36827600,0.0,0.0
2025-04-30,208.391740,212.653165,205.773148,211.577850,52286500,0.0,0.0

# testing fetch info function

In [8]:
result = fetcher.fetch_info("AAPL")

if result["error"]:
    print("Error:", result["error"])
else:
    df = pd.DataFrame([result["data"]])

df

,symbol,pe_ratio,forward_pe,peg_ratio,price_to_book,ev_to_ebitda,price_to_sales,profit_margin,operating_margin,roe,...,current_ratio,quick_ratio,free_cashflow,operating_cashflow,beta,market_cap,volume,avg_volume,dividend_yield,payout_ratio
0,AAPL,34.65526,29.173273,2.46,45.58686,26.408,9.215122,0.27037,0.35374,1.52021,...,0.974,0.845,1.063128e+11,1.354720e+11,1.109,4.014264e+12,33138070.0,46152330.0,0.38,0.1304